project:
  type: book
  output-dir: _book

book:
  title: "M 2.16 Microelectronic Circuit Design (MCD)"
  author:
    - name: "Mirco Meiners"
      orcid: "0000-0002-9709-4191"
      email: "Mirco.Meiners@hs-bremen.de"
      corresponding: true
      roles: "Lead author"
      affiliation:
        - id: hsb
        - name: "Hochschule Bremen - City University of Applied Sciences"
          city: "Bremen"
          state: "Germany"
          url: "https://www.hs-bremen.de/person/mimeiners/"
    - name: "Tim Ziemann"
      email: "Tim.Ziemann@hs-bremen.de"
      roles: "Supporting author"
      affiliation:
        - ref: hsb

  reader-mode: true

  page-footer:
    left: |
      M 2.16 Microelectronic Circuit Design (MCD)
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  # cover-image: images/hsb-logo.png
  favicon: images/hsb-logo.png
  site-url: https://mimeiners.github.io/amcd/
  repo-url: https://github.com/mimeiners/amcd/
  repo-branch: main
  repo-actions: [edit,issue]
  downloads: [pdf]

  chapters:
    - index.qmd
    
    - part: Lecture
      chapters:
        - lec/lec-01-intro.qmd
        - lec/lec-02a-analog_filter_design.qmd
        - lec/lec-03a-biquads.qmd
        # - lec/lec-04-ladders.qmd
        # - lec/lec-05-noise.qmd
        # - lec/lec-06-gm-ID.qmd
        # - lec/lec-07a-MCD6thEdChap10.qmd
        # - lec/lec-07b-MCD6thEdChap11.qmd
        # - lec/lec-07c-ota_simple_ic.qmd
        # - lec/lec-07d-ota_design_ic.qmd
        # - lec/lec-07e-ota_behavior_ic.qmd
        # - lec/lec-07p1-modelling_ic.qmd
        # - lec/lec-07p2-cs_amp_ic.qmd
        # - lec/lec-07p3-op_analysis_ic.qmd
        # - lec/lec-07p4-gain_and_ro.qmd
        # - lec/lec-07p5-intrinsic_cap_ic.qmd
        # - lec/lec-07p6-extrinsic_cap_ic.qmd
        # - lec/lec-07p7-miller_ic.qmd
        # - lec/lec-08-ota_cascode_ic.qmd
        # - lec/lec-09-integrators.qmd
        # - lec/lec-10-MCD6thEdChap12.qmd
        # - lec/lec-11-sc_filter.qmd
        # - lec/lec-12-adc_dac.qmd

    - part: Lab
      chapters:
        - lab/Analog_Inverter/index.qmd

    - part: Projects 2025
      chapters:
        - prj/elie1/index.qmd
        - prj/elie2/index.qmd
        - prj/elie3/index.qmd
        - prj/elie4/index.qmd
        - prj/elie5/index.qmd

    - references.qmd

  output-file: "mcd"
    
# Bibliography
bibliography: _bibliography/references.bib
csl: "https://raw.githubusercontent.com/citation-style-language/styles/master/ieee.csl"
# csl: _bibliography/ieee.csl


format:
  
  html:
    theme: flatly
    fontsize: 1.2em
    linestretch: 1.7
    # mainfont: Helvetica Neue, Helvetica, Arial, sans
    # monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    # backgroundcolor: "white"
    # fontcolor: "black"
    highlight-style: github
    # default-image-extension: svg

    # epub:
    #   theme: flatly
    #   fontsize: 1.2em
    #   linestretch: 1.7
    #   # mainfont: Helvetica Neue, Helvetica, Arial, sans
    #   # monofont: Cascadia Mono, Menlo, Consolas, Courier New, Courier
    #   # backgroundcolor: "white"
    #   # fontcolor: "black"
    #   highlight-style: github
    #   default-image-extension: svg

  # pdf:
  #   documentclass: scrbook
  #   classoption: [twoside]

  #   # keep-tex: true

  #   toc: true
  #   toc-depth: 3
  #   # toc-title: "Table of contents"
  #   # lof: true
  #   # lot: true

  #   number-sections: true
  #   number-depth: 2
        
  #   papersize: a4
    
  #   geometry:
  #     - inner=3cm
  #     - outer=4cm
  #     - top=3cm
  #     - bottom=4cm
  #     - headsep=22pt
  #     - headheight=11pt
  #     - footskip=33pt
  #     - ignorehead
  #     - ignorefoot
  #     - heightrounded

  #   fontsize: 11pt
  #   pdfengine: xelatex

  #   mainfont: "Calibri"
  #   monofont: "Courier New"
  #   mathfont: "TeX Gyre Termes Math"
    
    # include-in-header:
    #   - frontmatter/header.tex
    # template-partials:
    # - frontmatter/before-body.tex
    # - frontmatter/toc.tex
