# Conclusion

In this course the design process of an integrated circuit was experienced. Since all team members designed the universal biquad filter from [@AnalogSystemLabKitPROMANUAL] previously in their bachelors course as a discrete version, the differences in the workflows of discrete and integrated design became clear. For instance, in the discrete design, the behavior was mainly determined by the choice of the values for $R$ and $C$ and the effects of the PCB layout were negligible. However, for the integrated design these insights do not fully apply. In the integrated design process the behavior is determined by different aspects. In [@baker2008] the transconductance $g_m$ defines the filter coefficients and therefore the behavior of the filter. Different $g_m$ values for different OTAs lead to a different transfer functions. Examples are stated out in @sec-baker-design. The transconductance is also affected by the sizing of the transistor. The sizing of $W$ and $L$ in the integrated design can be understood similarly as the choice of $R$ and $C$. These links became clear by the help of this experiment and the challenges described in @sec-challenges. 

As mentioned in @sec-challenges, some issues with the circuit design were present. These challenges led to an enhanced understanding of the 5T-OTA and the design process of an integrated circuit itself. Oppositely, these challenges consumed a significant amount of the given time. Nevertheless, the project helped to comprehend the advanced possibilities of integrated circuit design as well as the different and more complex design process.

Such projects, in this collaborative environment, are considered by the team as very effective to understand the design process of integrated analog circuits. The room for individual design solutions enabled the team to experience more detailed insights to this topic. The error analysis in the step from ideal circuit to the real circuit contributed a lot to the understanding of the topic of circuit design.

Despite the required biquad filter is not working at all and no DRC- and LVS-conform layout is available, the developer team learned much. Due to the use of open source tools instead of commercial tools the learning process was not only limited to the design in one specific toolchain. Indeed, the learning process included much information about the complete toolchain in general and gave a good insight, which processes are covered in commercial tools in the background, but are necessary in an open source environment.