# Motivation
For many real life applications like audio processing, sensor signal conditioning and instrumentation, the signals can be corrupt due to unwanted noise and interference of the signals. One of the most important solution would be the use of filters especially analog filters with which it can be used to clean and shape signals before they are digitized or processed further.

The use of analog filter are advantageous over digital filters, even though it is way more flexible and programmable, because it has better power consumption, size, or cost constraints. Among analog filters, the biquad filter gets highlighted for its Second-order response which allows a precise control over frequency characteristics, flexibility to configure it as a low-pass, high-pass, band-pass or band-stop filters and its stability when implemented using op-amps and passive components.

This project focuses on designing, simulating, and implementing a biquad filter, using KiCad for schematic design, simulation, and PCB layout and ALSK tool kit for practical filter implementation and behavioral response testing using Red Pitaya. This whole projects motivates to have an understanding of how analog filters are practically implemented using op-amps, learn PCB design basics and fabrication, learn the usage of KICAD tool as well as integrating tools like ALSK and Red Pitaya into the design loop. Finally it gives a complete analog design experience, from concept to functional hardware, reinforcing both theoretical understanding and practical skills in analog electronics and system prototyping.

