# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/thesis/thesis_hp/Designs/Analog_Inverter/2_layout/analog_inverter.gds
load analog_inverter
select top cell
flatten analog_inverter_flat
load analog_inverter_flat
cellname delete analog_inverter -noprompt
cellname rename analog_inverter_flat analog_inverter
select top cell
extract path /foss/designs/thesis/thesis_hp/Designs/Analog_Inverter/3_kpex/analog_inverter__analog_inverter/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/thesis/thesis_hp/Designs/Analog_Inverter/3_kpex/analog_inverter__analog_inverter/magic_CC -o /foss/designs/thesis/thesis_hp/Designs/Analog_Inverter/3_kpex/analog_inverter__analog_inverter/magic_CC/analog_inverter.pex.spice
quit -noprompt